### ISSUE TITLE
Error: execution error at (backstage/templates/app-config.yaml:13:18): Provide App baseUrl in values

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer/helm-backstage#4]
helm upgrade -i backstage-0.1.1 redhat-developer-backstage/backstage results in the error message 
Error: execution error at (backstage/templates/app-config.yaml:13:18): Provide App baseUrl in values
and the readme.md does not indicate how the end-user should workaround that error

**Comment by burrsutter** [comment]
BASEURL=$(oc get dns cluster -o jsonpath='{.spec.baseDomain}')
oc new-project backstage
helm upgrade -i backstage-0.1.1 redhat-developer-backstage/backstage --set backstage.baseUrl=https://mybackstage-backstage-$BASEURL

**Comment by sabre1041** [comment]
@burrsutter has this issue been resolved?

**Comment by jmhbnz** [comment]
Encountered the same error - can confirm the `BASEURL` var based approach mentioned above worked around the helm error for me, thanks 👍🏻

**Comment by sabre1041** [comment]
Closing issue as solution has been provided
